### ISSUE TITLE
Interest in adding grunt tasks for mocha tests?

### ISSUE THREAD

**Issue by luislobo** [balderdashy/sails-generate-gruntfile#8]
We've added grunt tasks for mocha tests, do you want me to push a PR?

**Comment by mikermcneil** [comment]
@luislobo I think it would make an awesome generator override, but not sure about adding it to core right now.  If you put it together and publish it, I'd like to link it from our docs :+1:

**Comment by luislobo** [comment]
OK! I just need to find the extra time for developing it! :grin: Hopefully in a couple of weeks. Adding it to my list!
